pattern:
  id: "natural-organic"
  label: "ナチュラル・オーガニック"
  summary: "自然でやさしい。角を立てない。"
  suitable_for: ["product-ui", "marketing-site", "sns"]
  tokens:
    dtcg_json: "tonemana/catalog/tokens/natural-organic.tokens.json"
    css_vars: "tonemana/catalog/tokens/natural-organic.tokens.css"
  visual_rules:
    spacing_unit_px: 8
    radius_px: 12
    elevation: "low"
    imagery: "nature"
  writing_style:
    politeness: "neutral"
    sentence: "short"
    punctuation:
      exclamation: "avoid"
      emoji: "limited"
    do_dont:
      do: "読み込みに時間がかかっています。通信環境のよい場所でお試しください。"
      dont: "遅いです。やり直してください。"
  preview:
    html: "tonemana/catalog/previews/index.html?pattern=natural-organic"
