#!/usr/bin/env python3
"""Generate and verify a harness-scoped route lockfile from the model catalog.

Resolves every task class in `.agents/model-routing/task-classes.yml`
through `resolve_model_route.py` with the generated model catalog, and
writes the results to `.agents/model-routing/route-lockfile.json`.
The catalog's top-level `harness` is passed as the active harness; generation
fails if that identity is absent. Consumers must verify the lockfile harness
matches their active execution harness before using a concrete model ID.

Usage:
    python scripts/generate_route_lockfile.py --write
    python scripts/generate_route_lockfile.py --check   # fail if stale (CI)

Only Python stdlib is used.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

CATALOG_PATH = Path(".agents/model-routing/model-catalog.json")
TASK_CLASSES_PATH = Path(".agents/model-routing/task-classes.yml")
LOCKFILE_PATH = Path(".agents/model-routing/route-lockfile.json")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the harness-scoped route lockfile from the model catalog."
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="Rewrite the lockfile.")
    mode.add_argument("--check", action="store_true", help="Exit 1 if lockfile is stale.")
    parser.add_argument("--repo-root", default="", help="Repository root override.")
    return parser.parse_args()


def repo_root_from_args(explicit_root: str) -> Path:
    if explicit_root:
        return Path(explicit_root).resolve()
    return Path(__file__).resolve().parent.parent


def catalog_harness(catalog: dict) -> str:
    harness = catalog.get("harness")
    if not isinstance(harness, str) or not harness:
        raise ValueError(f"{CATALOG_PATH}: missing non-empty harness")
    return harness


def resolve_task_class(repo_root: Path, task_class: str, harness: str) -> dict:
    result = subprocess.run(
        [
            sys.executable,
            str(repo_root / "scripts" / "resolve_model_route.py"),
            task_class,
            "--catalog",
            str(repo_root / CATALOG_PATH),
            "--harness",
            harness,
            "--format",
            "json",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"resolver failed for task class {task_class}: {result.stderr.strip()}"
        )
    resolved = json.loads(result.stdout)
    if resolved.get("harness") != harness or resolved.get("catalog_harness") != harness:
        raise RuntimeError(
            f"resolver returned inconsistent harness identity for {task_class}"
        )
    return resolved


def build_lockfile(repo_root: Path) -> dict:
    task_classes = json.loads((repo_root / TASK_CLASSES_PATH).read_text(encoding="utf-8"))
    catalog = json.loads((repo_root / CATALOG_PATH).read_text(encoding="utf-8"))
    harness = catalog_harness(catalog)
    routes = {
        name: resolve_task_class(repo_root, name, harness)
        for name in sorted(task_classes["task_classes"])
    }
    return {
        "schema_version": 1,
        "harness": harness,
        "catalog_generated": catalog.get("generated"),
        "notes": (
            "Generated by scripts/generate_route_lockfile.py --write for the "
            "named harness. Do not use selected_model from another or unknown harness."
        ),
        "routes": routes,
    }


def render(lockfile: dict) -> str:
    return json.dumps(lockfile, indent=2) + "\n"


def main() -> int:
    args = parse_args()
    repo_root = repo_root_from_args(args.repo_root)
    for required in (CATALOG_PATH, TASK_CLASSES_PATH):
        if not (repo_root / required).is_file():
            print(f"error: {required} not found", file=sys.stderr)
            return 2

    try:
        expected = render(build_lockfile(repo_root))
    except (RuntimeError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    lock_path = repo_root / LOCKFILE_PATH
    current = lock_path.read_text(encoding="utf-8") if lock_path.is_file() else None

    if args.check:
        if current != expected:
            print(f"{LOCKFILE_PATH} is stale (run --write).")
            return 1
        print("Harness-scoped route lockfile is current.")
        return 0

    if current == expected:
        print("Harness-scoped route lockfile already current.")
    else:
        lock_path.write_text(expected, encoding="utf-8")
        print(f"Wrote {LOCKFILE_PATH} for harness {build_lockfile(repo_root)['harness']}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
